url: "https://viper12590.github.io"

collections:
  tags:
    output: true
    permalink: /tags/:path/
  people:
    output: true
    permalink: /people/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
  - scope:
      path: ''
      type: people
    values:
      layout: person
