url: "https://probonosociety.github.io"

title: "The Tipping Scales"

collections:
  tags:
    output: true
    permalink: /tags/:path/
  people:
    output: true
    permalink: /people/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
  - scope:
      path: ''
      type: people
    values:
      layout: person

page_excerpts: true

external_links:
  blog_email: "example@mail.com"
  main_email: "example@mail.com"
  main_website: "https://www.uobprobono.co.uk/"
  facebook: "https://www.facebook.com/uobprobosoc"
  twitter: "https://twitter.com/uobprobonosoc"
  instagram: "https://www.instagram.com/uobprobonosoc/"

